### ISSUE TITLE
Run /usr/bin/fdesetup usingrecoverykey on system load

### ISSUE THREAD

**Issue by erikng** [grahamgilbert/crypt#24] opened 2016-08-30 16:28 UTC
It would be great if on load, we could check to see if the RK is being used and log the event for future rotations.

This should ideally be in it's own script to reduce the dependency of network status from the `Checkin` tool.

**Comment by grahamgilbert** [comment] 2016-08-30 17:11
Yes. This would be simple, we should do this soon.

**Comment by erikng** [comment] 2016-08-30 17:41
Should I make this a flag with another launchd or launchd + new tool?

**Comment by grahamgilbert** [comment] 2016-08-30 17:44
Launch d with separate script would make the most sense.

**Comment by weswhet** [comment] 2016-12-06 19:32
i'm working on adding this into the auth plugin.

**Comment by alex030** [comment] 2017-02-08 14:25
I saw a first draft of the code in the version 2.2.x checking for "fdesetup usingrecoverykey" option. I tested this behaviour in the week before Christmas 2016. 
FV2 was enabled, I unlocked the device with the personal recovery key. Then the user was prompted at the Login Window to change the password. Once logged in, the "fdesetup usingrecoverykey" gave me the status true - AND the most important part: PLIST_PATH = '/private/var/root/crypt_output.plist' had the correct/used recovery key info stored. (Prefs Attr. RemovePlist was set to "false"). Was written once used the recovery key to unlock the hard drive. (Anyway - just saw this a few times - was kind of buggy - worked, not worked, worked ...)
Today I want to verify this on hardware instead of virtual machines. Have done the same steps like described before: "fdesetup usingrecoverykey" gives me status true, but PLIST_PATH = '/private/var/root/crypt_output.plist' has no recovery key info data. 
What am I doing wrong? How does fdesetup bring the used recovery key into the environment to work within the plugin?

**Comment by weswhet** [comment] 2017-02-09 00:29
@alex030 thanks for reporting. I'll have a look tomorrow. Can you verify which OS?

**Comment by alex030** [comment] 2017-02-09 08:36
I used 10.12.1 and 10.12.2

**Comment by weswhet** [comment] 2017-02-10 16:11
@alex030 I was unable to reproduce this on a VM. Can you post the crypt log at /var/log/crypt.log

**Comment by weswhet** [comment] 2017-02-13 17:42
@alex030 so after reading the entire comment when i'm not sleep deprived the recovery key is rotated using the old recovery key at `/private/var/root/crypt_output.plist` when `/Library/Crypt/Checkin` is run via launchd after login. The auth pluggin currently does not do any key rotation. Its also possible on your bare metal install that `RemovePlist` was set to True hence why the key was missing.

**Comment by weswhet** [comment] 2017-07-19 00:29
https://github.com/grahamgilbert/crypt2/pull/42 adds the code but it doesn't work due to bug that was supposed to be fixed in 10.12.4

**Comment by weswhet** [comment] 2017-08-04 16:28
addressed in https://github.com/grahamgilbert/crypt2/pull/50

**Closed as completed** 2018-01-25 01:34 UTC
