### ISSUE TITLE
On 10.13 Crypt does not write the key to disk

### ISSUE THREAD

**Issue by mikedodge04** [grahamgilbert/crypt#56] opened 2017-09-28 15:37 UTC
On 10.13 Crypt successfully encrypts but does not write the key to disk with a custom location.

**Comment by weswhet** [comment] 2017-09-28 16:08
Can you provide the version you are using, as well as logs using `sudo /usr/bin/log show --predicate '(subsystem == "com.grahamgilbert.crypt")' --style syslog --debug --info --last 24h`

**Comment by weswhet** [comment] 2017-12-01 21:50
Closing this as I can't reproduce.

**Closed as completed by weswhet** 2017-12-01 21:50 UTC
